events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /auth/ {
            proxy_pass http://auth_service:3004/;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /menu {
            proxy_pass http://catalogo_service:3001/menu;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /pedidos/crear {
            proxy_pass http://pedidos_service:3002/pedidos/crear;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /pedidos/recientes {
            proxy_pass http://pedidos_service:3002/pedidos/recientes;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/pedidos/([0-9]+)/calificar$ {
            proxy_pass http://pedidos_service:3002/pedidos/$1/calificar;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ruteo/ {
            proxy_pass http://10.201.191.162:3005/ruteo/;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws/pedidos {
            proxy_pass http://pedidos_service:3002/ws/pedidos;
            proxy_http_version 1.1;
            proxy_set_header Upgrade    $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host       $host;
            proxy_read_timeout  3600s;
            proxy_send_timeout  3600s;
        }

        # NUEVO: WebSocket de tracking por orden
        location ~ ^/ws/tracking/([0-9]+)$ {
            proxy_pass http://10.201.191.162:3005/ws/tracking/$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade    $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host       $host;
            proxy_read_timeout  3600s;
            proxy_send_timeout  3600s;
        }
    }
}