apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos
  namespace: saborgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos
  template:
    metadata:
      labels:
        app: pagos
    spec:
      containers:
      - name: pagos
        image: saborgo-pagos:v1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://saborgo_user:saborgo_password@db:5432/saborgo_db"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"